[env]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
	adafruit/Adafruit NeoPixel
	arduino-libraries/NTPClient
	knolleary/PubSubClient
	bblanchon/ArduinoJson
monitor_speed = 115200
board_build.partitions = min_spiffs.csv
build_flags = -D MQTT_MAX_PACKET_SIZE=4096

[env:c8_alpha]
build_src_filter = +<c8_alpha/> -<.git/> -<.svn/>

[env:mockup_v2]
build_src_filter = +<mockup_v2/> -<.git/> -<.svn/>
