[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
	adafruit/Adafruit NeoPixel
	arduino-libraries/NTPClient
	knolleary/PubSubClient
	bblanchon/ArduinoJson
monitor_speed = 115200
board_build.partitions = huge_app.csv
